### ISSUE TITLE
Download Issue (https://download.inventivetalent.org/gh/PacketListenerAPI/3.5.2-SNAPSHOT)

### ISSUE THREAD

**Issue by Nev3rGiveUp** [InventivetalentDev/download.inventivetalent.org#4]
**Which of the 3 download-options were you trying to use?** 
(Please select either adfly/donate/free) 
I tried every button , they were disabled.
**Please describe what the issue** 

I just wanted to download the latest PacketListenerAPI because of this error:

[12:12:30] [Netty Epoll Server IO #2/WARN]: java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name=entitiesById, types=[]}] in class class net.minecraft.server.v1_11_R1.WorldServer
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:186)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:39)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.reflection.resolver.FieldResolver.resolve(FieldResolver.java:85)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.mapmanager.MapManagerPlugin.getItemFrameById(MapManagerPlugin.java:155)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.mapmanager.event.MapInteractEvent.getItemFrame(MapInteractEvent.java:78)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.mapmanager.PacketListener$1.onReceive(PacketListener.java:77)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:131)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketReceive(PacketListenerAPI.java:133)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketReceive(ChannelAbstract.java:117)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:179)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at protocolsupport.protocol.pipeline.common.LogicHandler.channelRead(LogicHandler.java:41)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at protocolsupport.protocol.pipeline.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:12:30] [Netty Epoll Server IO #2/WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by InventivetalentDev** [comment]
Can you please check your browser's console for errors?
